
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-courses-w24-5pm-2
owner: ucsb-cs156-w24
repo_name: proj-courses-w24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOByAtbA","is_bot":false,"login":"livitsimple","name":""},"headRefName":"Olivia-PSEditPage-Frontend","number":24,"title":"FEATURE: Add edit page for personal schedules","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-2/pull/24"},{"author":{"id":"U_kgDOBdC95g","is_bot":false,"login":"Maria-Saucedo","name":""},"headRefName":"Maria-PC-Descriptions","number":23,"title":"FEATURE: More descriptive personal courses page","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-2/pull/23"}]
