
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-courses-w24-5pm-2
owner: ucsb-cs156-w24
repo_name: proj-courses-w24-5pm-2
pull_requests: [{"author":{"id":"U_kgDOB2-vOA","is_bot":false,"login":"jonathan-herring","name":"Jonathan Herring"},"headRefName":"jh-add-course-from-search","number":27,"title":"Jh Add Course From Search","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-2/pull/27"},{"author":{"id":"U_kgDOBqdaoA","is_bot":false,"login":"MeronDT","name":""},"headRefName":"merondt-CourseDescription","number":26,"title":"Merondt course description","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-2/pull/26"},{"author":{"id":"U_kgDOByAtbA","is_bot":false,"login":"livitsimple","name":""},"headRefName":"Olivia-UpdateJob-Frontend","number":25,"title":"Add frontend for job to update all courses in a range of quarters","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-2/pull/25"},{"author":{"id":"U_kgDOByAtbA","is_bot":false,"login":"livitsimple","name":""},"headRefName":"Olivia-PSEditPage-Frontend","number":24,"title":"FEATURE: Add edit page for personal schedules","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-2/pull/24"},{"author":{"id":"U_kgDOBdC95g","is_bot":false,"login":"Maria-Saucedo","name":""},"headRefName":"Maria-PC-Descriptions","number":23,"title":"FEATURE: More descriptive personal courses page","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-2/pull/23"},{"author":{"id":"U_kgDOB2_EDQ","is_bot":false,"login":"jiaqiguan2003","name":""},"headRefName":"Jiaqi-Simplify-Nav","number":22,"title":"REFACTOR: Simplify \"Personal schedule\" navigation","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-2/pull/22"},{"author":{"id":"U_kgDOB2_EDQ","is_bot":false,"login":"jiaqiguan2003","name":""},"headRefName":"Jiaqi-Schedule-Bug","number":21,"title":"BUG: Fixes Local Schedule Storage Bug","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-2/pull/21"}]
